### PR TITLE
Fix output for JSON-encoded responses

### LINKED ISSUE #22: `turnkey request` returns base64-encoded bytes instead of JSON
Here's a minimal repro:
```
$ turnkey request --host coordinator-beta.turnkey.io --path /public/v1/query/whoami --body '{"organizationId": "'"$ORGANIZATION_ID"'"}' -k test
"eyJvcmdhbml6YXRpb25JZCI6IjNiMDVmZTBkLTIxMjItNGE5Mi05ZDZkLWVkNWRiMjBkZWFiNiIsIm9yZ2FuaXphdGlvbk5hbWUiOiJSZWxlYXNlIDIwMjMtMDQtMjAiLCJ1c2VySWQiOiJjNWRiYjM0My0yYjZjLTQzY2ItOTA4MC1kNGQ1OGFmN2IxZmIiLCJ1c2VybmFtZSI6IlJvb3QgdXNlciJ9"
```

The workaround is easy enough: pipe to `jq -r | base64 -d`:
```
$ turnkey request --host coordinator-beta.turnkey.io --path /public/v1/query/whoami --body '{"organizationId": "'"$ORGANIZATION_ID"'"}' -k test | jq -r | base64
 -d
{"organizationId":"3b05fe0d-2122-4a92-9d6d-ed5db20deab6","organizationName":...etc...}
```

### PR DESCRIPTION
**Pull request by r-n-o**
Fixes #22, and introduces a new `local-build` target for local development.

Here's the result:
```
./build/turnkey request --host coordinator-beta.turnkey.io --path /public/v1/query/whoami --body '{"organizationId": "3b05fe0d-2122-4a92-9d6d-ed5db20deab6"}' -k test -o yaml
organizationId: 3b05fe0d-2122-4a92-9d6d-ed5db20deab6
organizationName: Release 2023-04-20
userId: c5dbb343-2b6c-43cb-9080-d4d58af7b1fb
username: Root user
```

```
./build/turnkey request --host coordinator-beta.turnkey.io --path /public/v1/query/whoami --body '{"organizationId": "3b05fe0d-2122-4a92-9d6d-ed5db20deab6"}' -k test
{
   "organizationId": "3b05fe0d-2122-4a92-9d6d-ed5db20deab6",
   "organizationName": "Release 2023-04-20",
   "userId": "c5dbb343-2b6c-43cb-9080-d4d58af7b1fb",
   "username": "Root user"
}

### CODE REVIEW

File: src/cmd/format.go [hunk 1]
```diff
@@ -62,3 +63,20 @@ type ResponseError struct {
 func (r *ResponseError) Error() string {
 	return fmt.Sprintf("%d: %s", r.Code, r.Text)
 }
+
+// In case the payload is already JSON-encoded, try decoding it before passing it on.
+// Otherwise it leads to double-encoding.
```
Comment (Ulexus) [inline src/cmd/format.go:68]: Hah!  Thanks!

**Review by Ulexus — APPROVED** [review]
